# This is a simple pod test
apiVersion: v1
kind: Pod
metadata:
  name: trustme-demo
spec:
  securityContext:
    runAsUser: 100 #nginx
    fsGroup: 101 #nginx
  containers:
  - name: sec-trust-demo
    image: shaker242/dlogo:trust
    securityContext:
      allowPrivilegeEscalation: false