version: "3"
services:
  trustweb:
    image: shaker242/dlogo:trust
    ports:
      - "8080"
    networks:
      - trustnet
    deploy:
      mode: replicated
      replicas: 4
      placement:
        constraints: 
          - node.role==worker
          - node.platform.os==linux

networks:
  trustnet:
    driver: overlay