---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ex-trust
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ex-trust
    spec:
      containers:
      - name: ex-trust
        image: shaker242/dlogo:trust
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          runAsUser: 100
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: false
      nodeSelector:
        kubernetes.io/hostname: linux3
---
apiVersion: v1
kind: Service
metadata:
  name: ex-trust
  labels:
    name: ex-trust
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 88
    targetPort: 8080
  selector:
    name: ex-trust
